#!/bin/zsh
clear
yacc -d exprtree.y
lex exprtree.l
gcc y.tab.c lex.yy.c -o exprtree
clear

echo "📑 Stage 1 : Code generation for Arithmetic Expressions\n"

echo "Enter Arithmetic Expression: "

./exprtree

if [ $? -eq 0 ] 
then

	echo "\n🚀 Executing target.xsm\n"

	cd ../..
	./xsm -l library.lib -e Stages/1/target.xsm

fi
