#!/bin/zsh
clear
yacc -d exprtree.y
lex exprtree.l
gcc y.tab.c lex.yy.c -o exprtree
clear

echo "📑 Stage 1 : Code generation for Arithmetic Expressions\n"
echo "Exercise 1"
echo "Exercise 2"
echo "Exercise 3"
echo "\nChoose option (1-3): "
read optionNum
echo "\nOption: $optionNum\n"

./exprtree
cd ../..
./xsm -l library.lib -e Stages/1/target.xsm
