#!/bin/zsh
clear
yacc -d ast.y
lex ast.l
gcc y.tab.c lex.yy.c ast.c codegen.c ../Functions/reg.c ../Functions/label.c ../Functions/xsm_syscalls.c ../Functions/xsm_library.c -g -o ast
 # clear

echo "⏳ Compiling $1:\n"
cat -n $1

./ast $1 < $1

if [ $? -eq 0 ]
then
	cat target.xsm > $1.xsm
	echo "\n🚀 Running $1.xsm\n"

	cd ../..
	./xsm -l library.lib -e Stages/3/$1.xsm
fi
