#!/bin/zsh
clear

cd ./Frontend

byacc -d -v -t ast.y
lex ast.l
gcc y.tab.c lex.yy.c ast.c ../Backend/codegen.c ../Data_Structures/loopStack.c ../Data_Structures/typeTable.c ../Data_Structures/GSTable.c ../Data_Structures/paramStruct.c ../Data_Structures/LSTable.c ../Data_Structures/classTable.c ../Data_Structures/memberFuncList.c ../Functions/reg.c ../Functions/label.c ../Functions/xsm_syscalls.c ../Functions/xsm_library.c ../Functions/stackMemory.c ../Functions/stringMan.c ../Functions/typeCheck.c -g -o ast
 # clear

echo "⏳ Compiling $1.expl"
printf '%.s─' $(seq 1 $(tput cols))
printf "\n"

cat -n ../Input_Files/8/$1.expl
printf "\n"
printf '%.s─' $(seq 1 $(tput cols))

./ast $1 < ../Input_Files/8/$1.expl

# echo "Program returned: $?"

if [ $? -eq 0 ]
then

	cd ../Backend

	lex labelTranslator.l
  	gcc lex.yy.c ../Functions/label.c  -g -o labelTranslator
  	./labelTranslator

	echo "\n🚀 Running target.xsm\n"

	cd ../../..
	./xsm -l library.lib -e Stages/8/Target_Files/target.xsm $2
fi
