#!/bin/zsh
clear
yacc -d -t ast.y
lex ast.l
gcc y.tab.c lex.yy.c ast.c intepreter.c ../Functions/typeCheck.c  -g -o ast
#clear

echo "$(tput bold)🔨 Expl Intepreter, please enter your code\n$(tput sgr0)"
# cat -n $1

./ast
