#!/bin/zsh
clear
yacc -d ast.y
lex ast.l
gcc y.tab.c lex.yy.c ../Functions/copyFile.c -g -o ast
clear

echo "⏳ Compiling $1:\n"
cat -n $1

./ast $1 < $1

if [ $? -eq 0 ]
then
	cat target.xsm > $1.xsm
fi
