#!/bin/zsh
clear
yacc -d ast.y
lex ast.l
gcc y.tab.c lex.yy.c ast.c  ../Functions/copyFile.c ./Intepreter/intepreter.c  -g -o ast
clear

echo "⏳ Compiling $1:\n"
cat -n $1

./ast $1 < $1

if [ $? -eq 0 ]
then
	echo "\n🚀 Running target.xsm\n"

	cd ../..
	./xsm -l library.lib -e Stages/2/target.xsm
fi
