#!/bin/zsh
clear

cd ./Frontend

byacc -d -v -t ast.y
lex ast.l
gcc y.tab.c lex.yy.c ast.c ../Backend/codegen.c ../Data_Structures/loopStack.c ../Data_Structures/declarationsTree.c ../Data_Structures/globalSymbolTable.c ../Functions/reg.c ../Functions/label.c ../Functions/xsm_syscalls.c ../Functions/xsm_library.c ../Functions/stackMemory.c ../Functions/stringMan.c -g -o ast
 # clear

echo "⏳ Compiling $1"
printf '%.s─' $(seq 1 $(tput cols))

cat -n ../Input_Files/$1
printf '%.s─' $(seq 1 $(tput cols))

./ast $1 < ../Input_Files/$1

# echo "Program returned: $?"

if [ $? -eq 0 ]
then

	cd ../Backend

	lex labelTranslator.l
  	gcc lex.yy.c ../Functions/label.c  -g -o labelTranslator
  	./labelTranslator

	echo "\n🚀 Running target.xsm\n"

	cd ../../..
	./xsm -l library.lib -e Stages/4/Target_Files/target.xsm $2
fi
