#!/bin/zsh
clear

cd ./Frontend

yacc -d ast.y
lex ast.l
gcc y.tab.c lex.yy.c ast.c ../Backend/codegen.c ../Data_Structures/loopStack.c ../Data_Structures/declarationsTree.c ../Data_Structures/globalSymbolTable.c ../Functions/reg.c ../Functions/label.c ../Functions/xsm_syscalls.c ../Functions/xsm_library.c ../Functions/stackMemory.c -g -o ast
 # clear

echo "⏳ Compiling $1:\n"
cat -n ../Input_Files/$1

./ast $1 < ../Input_Files/$1

#echo $?

if [ $? -eq 0 ]
then

	cd ../Backend

	lex labelTranslator.l
  	gcc lex.yy.c ../Functions/label.c  -g -o labelTranslator
  	./labelTranslator

	echo "\n🚀 Running target.xsm\n"

	cd ../../..
	./xsm -l library.lib -e Stages/4/Target_Files/target.xsm
fi
